name: Test-build pull-requests

on:
  pull_request:

jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v1
    - run: |
        docker buildx build \
        --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x \
        --file core-stable.Dockerfile .

  test-core18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v1
    - run: |
        docker buildx build \
        --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x \
        --file core18-stable.Dockerfile .

  test-core20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v1
    - run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x \
        --file core20-stable.Dockerfile .
